%YAML:1.0
---
#camera calibration 
model_type:   PINHOLE
camera_name:  camera
image_width:  1600
image_height: 1100

# NTU VIRAL datasets
distortion_parameters:
   k1: -0.13309
   k2:  0.08143
   p1:  0.00023
   p2:  0.00043
projection_parameters:
   fx: 903.56583
   fy: 902.47901
   cx: 800.04169
   cy: 556.80513